version: "1.0"
info:
  model: int-scaffold
packages:
- name: TestLocaldevProject
  gitServerName: BT
  gitUrl: https://github.com/Bharathi-Thammisetty-IBM
  gitUsername: Bharathi-Thammisetty-IBM
  gitBranch: main
- name: WmJDBCAdapter
  version: 10.3.0.0.34
  wpmServer: https://packages.webmethods.io
  wpmRegistry: licensed
services:
- serviceName: project.testlocaldev.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections:dbConnBT1
  packages:
  - name: TestLocaldevProject
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
- serviceName: project.testlocaldev.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections:dbconn1
  packages:
  - name: TestLocaldevProject
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
- serviceName: project.testlocaldev.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.operations.actions:se
  packages:
  - name: TestLocaldevProject
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
- serviceName: project.testlocaldev.integrations:DB_git
  packages:
  - name: TestLocaldevProject
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
configurationVariables:
  ? artConnection.TestLocaldevProject.project.testlocaldev.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.dbconn1.connectionManagerSettings.maximumPoolSize
  : "10"
  ? artConnection.TestLocaldevProject.project.testlocaldev.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.dbConnBT1.connectionSettings.user
  : JDBC_BVT
  ? artConnection.TestLocaldevProject.project.testlocaldev.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.dbconn1.connectionSettings.dbType
  : ORACLE
  ? artConnection.TestLocaldevProject.project.testlocaldev.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.dbconn1.connectionSettings.driverType
  : Progress速 DataDirect速
  ? artConnection.TestLocaldevProject.project.testlocaldev.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.dbConnBT1.connectionManagerSettings.poolable
  : "true"
  ? artConnection.TestLocaldevProject.project.testlocaldev.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.dbconn1.connectionSettings.transactionType
  : LOCAL_TRANSACTION
  ? artConnection.TestLocaldevProject.project.testlocaldev.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.dbconn1.connectionManagerSettings.startupBackoffSecs
  : "10"
  ? artConnection.TestLocaldevProject.project.testlocaldev.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.dbConnBT1.connectionSettings.serverName
  : adapter-oracle-121-on-amazonrds.cdmjexwbzoym.us-east-1.rds.amazonaws.com
  ? artConnection.TestLocaldevProject.project.testlocaldev.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.dbconn1.connectionSettings.serverName
  : adapter-oracle-121-on-amazonrds.cdmjexwbzoym.us-east-1.rds.amazonaws.com
  ? artConnection.TestLocaldevProject.project.testlocaldev.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.dbconn1.connectionSettings.password
  : "{AES}gOk3wygfWVjWqDc4SLehnQ=="
  ? artConnection.TestLocaldevProject.project.testlocaldev.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.dbconn1.connectionManagerSettings.blockingTimeout
  : "1000"
  ? artConnection.TestLocaldevProject.project.testlocaldev.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.dbConnBT1.connectionSettings.datasourceClass
  : com.wm.dd.jdbcx.oracle.OracleDataSource
  ? artConnection.TestLocaldevProject.project.testlocaldev.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.dbConnBT1.connectionManagerSettings.startupRetryCount
  : "0"
  ? artConnection.TestLocaldevProject.project.testlocaldev.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.dbconn1.connectionSettings.networkProtocol
  : ""
  ? artConnection.TestLocaldevProject.project.testlocaldev.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.dbconn1.connectionSettings.keyStore
  : ""
  ? artConnection.TestLocaldevProject.project.testlocaldev.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.dbConnBT1.connectionManagerSettings.minimumPoolSize
  : "1"
  ? artConnection.TestLocaldevProject.project.testlocaldev.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.dbConnBT1.connectionManagerSettings.expireTimeout
  : "1000"
  ? artConnection.TestLocaldevProject.project.testlocaldev.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.dbConnBT1.connectionSettings.trustStore
  : ""
  ? artConnection.TestLocaldevProject.project.testlocaldev.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.dbConnBT1.connectionSettings.dbType
  : ORACLE
  ? artConnection.TestLocaldevProject.project.testlocaldev.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.dbConnBT1.connectionSettings.networkProtocol
  : ""
  ? artConnection.TestLocaldevProject.project.testlocaldev.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.dbConnBT1.connectionSettings.keyStore
  : ""
  ? artConnection.TestLocaldevProject.project.testlocaldev.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.dbconn1.connectionSettings.otherProperties
  : ""
  ? artConnection.TestLocaldevProject.project.testlocaldev.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.dbConnBT1.connectionSettings.password
  : "{AES}gOk3wygfWVjWqDc4SLehnQ=="
  ? artConnection.TestLocaldevProject.project.testlocaldev.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.dbConnBT1.connectionSettings.otherProperties
  : ""
  ? artConnection.TestLocaldevProject.project.testlocaldev.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.dbConnBT1.connectionSettings.portNumber
  : "1521"
  ? artConnection.TestLocaldevProject.project.testlocaldev.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.dbconn1.connectionManagerSettings.poolIncrementSize
  : "1"
  ? artConnection.TestLocaldevProject.project.testlocaldev.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.dbConnBT1.connectionEnabled
  : "false"
  ? artConnection.TestLocaldevProject.project.testlocaldev.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.dbconn1.connectionSettings.trustStore
  : ""
  ? artConnection.TestLocaldevProject.project.testlocaldev.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.dbconn1.connectionManagerSettings.startupRetryCount
  : "0"
  ? artConnection.TestLocaldevProject.project.testlocaldev.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.dbconn1.connectionSettings.databaseName
  : ORCL
  ? artConnection.TestLocaldevProject.project.testlocaldev.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.dbconn1.connectionManagerSettings.heartBeatInterval
  : "0"
  ? artConnection.TestLocaldevProject.project.testlocaldev.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.dbconn1.connectionManagerSettings.poolable
  : "true"
  ? artConnection.TestLocaldevProject.project.testlocaldev.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.dbConnBT1.connectionManagerSettings.maximumPoolSize
  : "10"
  ? artConnection.TestLocaldevProject.project.testlocaldev.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.dbConnBT1.connectionManagerSettings.startupBackoffSecs
  : "10"
  ? artConnection.TestLocaldevProject.project.testlocaldev.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.dbconn1.connectionSettings.datasourceClass
  : com.wm.dd.jdbcx.oracle.OracleDataSource
  ? artConnection.TestLocaldevProject.project.testlocaldev.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.dbConnBT1.connectionManagerSettings.poolIncrementSize
  : "1"
  ? artConnection.TestLocaldevProject.project.testlocaldev.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.dbconn1.connectionSettings.user
  : JDBC_BVT
  ? artConnection.TestLocaldevProject.project.testlocaldev.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.dbConnBT1.connectionSettings.transactionType
  : LOCAL_TRANSACTION
  ? artConnection.TestLocaldevProject.project.testlocaldev.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.dbconn1.connectionManagerSettings.expireTimeout
  : "1000"
  ? artConnection.TestLocaldevProject.project.testlocaldev.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.dbConnBT1.connectionSettings.driverType
  : Progress速 DataDirect速
  ? artConnection.TestLocaldevProject.project.testlocaldev.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.dbconn1.connectionEnabled
  : "false"
  ? artConnection.TestLocaldevProject.project.testlocaldev.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.dbConnBT1.connectionSettings.databaseName
  : ORCL
  ? artConnection.TestLocaldevProject.project.testlocaldev.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.dbConnBT1.connectionManagerSettings.blockingTimeout
  : "1000"
  ? artConnection.TestLocaldevProject.project.testlocaldev.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.dbconn1.connectionManagerSettings.minimumPoolSize
  : "1"
  ? artConnection.TestLocaldevProject.project.testlocaldev.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.dbConnBT1.connectionManagerSettings.heartBeatInterval
  : "0"
  ? artConnection.TestLocaldevProject.project.testlocaldev.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.dbconn1.connectionSettings.portNumber
  : "1521"
